### ISSUE TITLE
Nav, browser testing

### ISSUE THREAD

**Issue by arial-alisha** [arial-alisha/infographic-effects-interactivity#2]
Hi Thomas, @thomasjbradley  

Just a few other questions before class tomorrow.  
-My animations don't seem to work in some safari browsers, like mine but they do work in others.  
-I tried to make a navigation at the top so I could incorporate smooth scrolling but it is all squished and I am not too sure what else to do to it. If you have any tips, let me know! 

Thanks, 
Alisha Arial

**Comment by thomasjbradley** [comment]
_Safari animation issues:_

The vendor prefixes are missing in many places, you'd have to do something like this:

``` css
.thing {
  -webkit-animation: blah 5s linear;
  animation: blah 5s linear;
}

@-webkit-keyframes blah {

}

@keyframes blah {

}
```

---

_Nav:_

It's because it's inside a `.grid` but not inside a `.unit`.
